/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moredocofee;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author john
 */
public class pdisplayy extends javax.swing.JFrame {

    /**
     * Creates new form pdisplayy
     */
    static final String server ="jdbc:mysql://localhost:3306/moredo";
    public String card_number="";
    private PreparedStatement addpat=null;
    Connection con=null;
    Statement sql=null;
    ResultSet rs;
    public pdisplayy() {
        this.rs = null;
        initComponents();
        DBConnect();
        ImageIcon image = new javax.swing.ImageIcon(getClass().getResource("ic1.png"));
        Image ic = image.getImage();
        setIconImage(ic);
       
    }
 private void DBConnect() 
         {
            try 
            {
                con=DriverManager.getConnection
                        (
              server,"root",""  
                        );
                
            }
            catch(SQLException sqlException)
            {
                sqlException.printStackTrace();
            }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbDateFind = new javax.swing.JLabel();
        jfindphoto = new javax.swing.JLabel();
        lbphotofind = new javax.swing.JLabel();
        lbContactFind1 = new javax.swing.JLabel();
        lbFnameFind = new javax.swing.JLabel();
        lbContactFind2 = new javax.swing.JLabel();
        lbAgeFind = new javax.swing.JLabel();
        lbGenderFind = new javax.swing.JLabel();
        lbContactFind3 = new javax.swing.JLabel();
        lbEmailFind = new javax.swing.JLabel();
        lbContactFind = new javax.swing.JLabel();
        lbAddressFind = new javax.swing.JLabel();
        lbQualifiFind = new javax.swing.JLabel();
        lbBloodFind = new javax.swing.JLabel();
        txtAddressFind = new javax.swing.JTextField();
        txtAgeFind = new javax.swing.JTextField();
        txtGenderFind = new javax.swing.JTextField();
        txtEmailFind = new javax.swing.JTextField();
        txtContactFind = new javax.swing.JTextField();
        txtsalaryfind = new javax.swing.JTextField();
        txtlevelfind = new javax.swing.JTextField();
        txttypefind = new javax.swing.JTextField();
        txtFnameFind = new javax.swing.JTextField();
        txtQualificationFind = new javax.swing.JTextField();
        txtBloodFind = new javax.swing.JTextField();
        txtDateFind = new javax.swing.JTextField();
        txtIDFind = new javax.swing.JTextField();
        lbFnameFind1 = new javax.swing.JLabel();
        jBdelete = new javax.swing.JButton();
        txtpermission = new javax.swing.JTextField();
        lbContactFind4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel9.setText("Employee Information");

        jButton1.setBackground(new java.awt.Color(111, 78, 55));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jButton1.setText("Update");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbDateFind.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        lbDateFind.setForeground(new java.awt.Color(111, 78, 55));
        lbDateFind.setText("Date of Joining");

        lbphotofind.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        lbphotofind.setForeground(new java.awt.Color(111, 78, 55));
        lbphotofind.setText("Photo");

        lbContactFind1.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        lbContactFind1.setForeground(new java.awt.Color(111, 78, 55));
        lbContactFind1.setText("Salary");

        lbFnameFind.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        lbFnameFind.setForeground(new java.awt.Color(111, 78, 55));
        lbFnameFind.setText("Full Name");

        lbContactFind2.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        lbContactFind2.setForeground(new java.awt.Color(111, 78, 55));
        lbContactFind2.setText("Level of Education");

        lbAgeFind.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        lbAgeFind.setForeground(new java.awt.Color(111, 78, 55));
        lbAgeFind.setText("Age");

        lbGenderFind.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        lbGenderFind.setForeground(new java.awt.Color(111, 78, 55));
        lbGenderFind.setText("Gender");

        lbContactFind3.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        lbContactFind3.setForeground(new java.awt.Color(111, 78, 55));
        lbContactFind3.setText("Type");

        lbEmailFind.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        lbEmailFind.setForeground(new java.awt.Color(111, 78, 55));
        lbEmailFind.setText("Email");

        lbContactFind.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        lbContactFind.setForeground(new java.awt.Color(111, 78, 55));
        lbContactFind.setText("Contact Number");

        lbAddressFind.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        lbAddressFind.setForeground(new java.awt.Color(111, 78, 55));
        lbAddressFind.setText("Address");

        lbQualifiFind.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        lbQualifiFind.setForeground(new java.awt.Color(111, 78, 55));
        lbQualifiFind.setText("Specification");

        lbBloodFind.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        lbBloodFind.setForeground(new java.awt.Color(111, 78, 55));
        lbBloodFind.setText("Blood Type");

        txtAddressFind.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtAddressFind.setBorder(null);
        txtAddressFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressFindActionPerformed(evt);
            }
        });

        txtAgeFind.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtAgeFind.setBorder(null);
        txtAgeFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeFindActionPerformed(evt);
            }
        });

        txtGenderFind.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtGenderFind.setBorder(null);
        txtGenderFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderFindActionPerformed(evt);
            }
        });

        txtEmailFind.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtEmailFind.setBorder(null);
        txtEmailFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailFindActionPerformed(evt);
            }
        });

        txtContactFind.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtContactFind.setBorder(null);
        txtContactFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactFindActionPerformed(evt);
            }
        });

        txtsalaryfind.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtsalaryfind.setBorder(null);
        txtsalaryfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsalaryfindActionPerformed(evt);
            }
        });

        txtlevelfind.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtlevelfind.setBorder(null);
        txtlevelfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlevelfindActionPerformed(evt);
            }
        });

        txttypefind.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txttypefind.setBorder(null);
        txttypefind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttypefindActionPerformed(evt);
            }
        });

        txtFnameFind.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtFnameFind.setBorder(null);
        txtFnameFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnameFindActionPerformed(evt);
            }
        });

        txtQualificationFind.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtQualificationFind.setBorder(null);
        txtQualificationFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQualificationFindActionPerformed(evt);
            }
        });

        txtBloodFind.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtBloodFind.setBorder(null);
        txtBloodFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodFindActionPerformed(evt);
            }
        });

        txtDateFind.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtDateFind.setBorder(null);
        txtDateFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateFindActionPerformed(evt);
            }
        });

        txtIDFind.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtIDFind.setBorder(null);
        txtIDFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDFindActionPerformed(evt);
            }
        });

        lbFnameFind1.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        lbFnameFind1.setForeground(new java.awt.Color(111, 78, 55));
        lbFnameFind1.setText("ID No.");

        jBdelete.setBackground(new java.awt.Color(111, 78, 55));
        jBdelete.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jBdelete.setText("Delete");
        jBdelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBdeleteMouseClicked(evt);
            }
        });
        jBdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdeleteActionPerformed(evt);
            }
        });

        txtpermission.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtpermission.setBorder(null);
        txtpermission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpermissionActionPerformed(evt);
            }
        });

        lbContactFind4.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        lbContactFind4.setForeground(new java.awt.Color(111, 78, 55));
        lbContactFind4.setText("No of permission Days left");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addGap(212, 212, 212)
                .addComponent(jLabel9)
                .addGap(200, 200, 200))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbContactFind3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbFnameFind1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lbContactFind2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbContactFind1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbFnameFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbAgeFind, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbGenderFind, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbEmailFind, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbContactFind, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lbContactFind4))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttypefind)
                            .addComponent(txtpermission, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtGenderFind, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAgeFind, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEmailFind)
                                        .addComponent(txtContactFind, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                        .addComponent(txtsalaryfind, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtlevelfind))
                                    .addComponent(txtFnameFind, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIDFind, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBdelete)
                        .addGap(51, 51, 51)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lbBloodFind, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbDateFind, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbphotofind, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtDateFind, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtBloodFind, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbQualifiFind, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbAddressFind, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddressFind, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQualificationFind, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jfindphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIDFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbFnameFind1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbFnameFind)
                            .addComponent(txtFnameFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddressFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbAddressFind))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAgeFind)
                            .addComponent(txtAgeFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbQualifiFind)
                            .addComponent(txtQualificationFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbBloodFind)
                            .addComponent(txtBloodFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbGenderFind)
                                    .addComponent(txtGenderFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbEmailFind)
                                    .addComponent(txtEmailFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbphotofind))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(lbContactFind))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtContactFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbContactFind1)
                                    .addComponent(txtsalaryfind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbContactFind2)
                                    .addComponent(txtlevelfind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbContactFind3)
                                    .addComponent(txttypefind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtpermission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbContactFind4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDateFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbDateFind))
                                .addGap(18, 18, 18)
                                .addComponent(jfindphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(74, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jBdelete))
                        .addGap(51, 51, 51))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(456, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
            String ID = txtIDFind.getText();    
            String name = txtFnameFind.getText();
            String gender = txtGenderFind.getText();
            String age = txtAgeFind.getText();
            String email = txtEmailFind.getText();
            String contact = txtContactFind.getText();
            String dep = txtQualificationFind.getText();
            String address = txtAddressFind.getText();
            String blood = txtBloodFind.getText();
            String datej = txtDateFind.getText();
            String type = txttypefind.getText();
            String salary = txtsalaryfind.getText();
            String level = txtlevelfind.getText();
            String photo = jfindphoto.getText();
            String permission = txtpermission.getText();
        try{
            sql=con.createStatement();
         ResultSet myresult=sql.executeQuery("select * from employee where ID=" + ID);
        
        while(myresult.next())  
        {
       
       PreparedStatement idp1 = con.prepareStatement
        ("UPDATE employee SET Name =?, Gender =?, age=?, Email=?, Contactno=?, Specification=?, Address=?, Blood=?, Datejoining=?, photo=?, Type=?, Salary=?, Level=? ,permission=?  Where ID = '"+ID+"'");
            idp1.setString(1, name);
            idp1.setString(2, gender);
            idp1.setString(3, age);
            idp1.setString(4, email);
            idp1.setString(5, contact);
            idp1.setString(6, dep);
            idp1.setString(7, address);
            idp1.setString(8, blood);
            idp1.setString(9, datej);
            idp1.setString(10, photo);
            idp1.setString(11, type);
            idp1.setString(12, salary);
            idp1.setString(13, level);
            idp1.setString(14, permission);
            idp1.executeUpdate();
            
                JOptionPane.showMessageDialog(null, "Employee Updated sucessfully!");
        }
        } catch (SQLException ex) {
           
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtAgeFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeFindActionPerformed

    private void txtGenderFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderFindActionPerformed

    private void txtEmailFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailFindActionPerformed

    private void txtContactFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactFindActionPerformed

    private void txtsalaryfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsalaryfindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsalaryfindActionPerformed

    private void txtlevelfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlevelfindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlevelfindActionPerformed

    private void txttypefindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttypefindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttypefindActionPerformed

    private void txtFnameFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnameFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnameFindActionPerformed

    private void txtQualificationFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQualificationFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualificationFindActionPerformed

    private void txtBloodFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodFindActionPerformed

    private void txtDateFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateFindActionPerformed

    private void txtAddressFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressFindActionPerformed

    private void txtIDFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDFindActionPerformed

    private void jBdeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBdeleteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBdeleteMouseClicked

    private void jBdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdeleteActionPerformed
        // TODO add your handling code here:
        DBConnect();
         int option = JOptionPane.showConfirmDialog(rootPane,
                    "Are you sure you want to Delete?", "Delete confirmation", JOptionPane.YES_NO_OPTION);
                 try { 
           
            String query = "delete from employee where ID = '" + txtIDFind.getText()+"'";
            PreparedStatement pst = con.prepareStatement(query);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Employee sucessfully deleted");
      
        
       } catch (SQLException ex) { 
         Logger.getLogger(moredo.class.getName()).log(Level.SEVERE, null, ex);
     }
                 txtFnameFind.setText("");
                 txtAgeFind.setText("");
                 txtGenderFind.setText("");
                 txtContactFind.setText("");
                 txtEmailFind.setText("");
                 txtsalaryfind.setText("");
                 txtlevelfind.setText("");
                 txttypefind.setText("");
                 txtAddressFind.setText("");
                 txtQualificationFind.setText("");
                 txtBloodFind.setText("");
                 txtDateFind.setText("");
                 jfindphoto.setIcon(new ImageIcon(""));
    }//GEN-LAST:event_jBdeleteActionPerformed

    private void txtpermissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpermissionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpermissionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pdisplayy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pdisplayy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pdisplayy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pdisplayy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pdisplayy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBdelete;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jfindphoto;
    private javax.swing.JLabel lbAddressFind;
    private javax.swing.JLabel lbAgeFind;
    private javax.swing.JLabel lbBloodFind;
    private javax.swing.JLabel lbContactFind;
    private javax.swing.JLabel lbContactFind1;
    private javax.swing.JLabel lbContactFind2;
    private javax.swing.JLabel lbContactFind3;
    private javax.swing.JLabel lbContactFind4;
    private javax.swing.JLabel lbDateFind;
    private javax.swing.JLabel lbEmailFind;
    private javax.swing.JLabel lbFnameFind;
    private javax.swing.JLabel lbFnameFind1;
    private javax.swing.JLabel lbGenderFind;
    private javax.swing.JLabel lbQualifiFind;
    private javax.swing.JLabel lbphotofind;
    public javax.swing.JTextField txtAddressFind;
    public javax.swing.JTextField txtAgeFind;
    public javax.swing.JTextField txtBloodFind;
    public javax.swing.JTextField txtContactFind;
    public javax.swing.JTextField txtDateFind;
    public javax.swing.JTextField txtEmailFind;
    public javax.swing.JTextField txtFnameFind;
    public javax.swing.JTextField txtGenderFind;
    public javax.swing.JTextField txtIDFind;
    public javax.swing.JTextField txtQualificationFind;
    public javax.swing.JTextField txtlevelfind;
    public javax.swing.JTextField txtpermission;
    public javax.swing.JTextField txtsalaryfind;
    public javax.swing.JTextField txttypefind;
    // End of variables declaration//GEN-END:variables
}
